In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\aggar\Downloads\archive (4)\car_prices.csv")

In [4]:
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  str
 2   model         548438 non-null  str
 3   trim          548186 non-null  str
 4   body          545642 non-null  str
 5   transmission  493485 non-null  str
 6   vin           558833 non-null  str
 7   state         558837 non-null  str
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  str
 11  interior      558088 non-null  str
 12  seller        558837 non-null  str
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  str
dtypes: float64(4), int64(1), str(11)
memory usage: 68.2 MB

In [26]:
df.shape

(548400, 24)

In [9]:
df.isnull().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [8]:
df.drop(columns=['vin'], inplace=True)

In [10]:
df.dropna(subset=[
    'make',
    'model',
    'mmr',
    'sellingprice',
    'saledate'
], inplace=True)

In [11]:
df['trim'] = df['trim'].fillna('Unknown')
df['body'] = df['body'].fillna('Unknown')
df['transmission'] = df['transmission'].fillna('Unknown')
df['color'] = df['color'].fillna('Unknown')
df['interior'] = df['interior'].fillna('Unknown')

In [12]:
df['condition'] = df['condition'].fillna(df['condition'].median())
df['odometer'] = df['odometer'].fillna(df['odometer'].median())

In [13]:
df.isnull().sum()

year            0
make            0
model           0
trim            0
body            0
transmission    0
state           0
condition       0
odometer        0
color           0
interior        0
seller          0
mmr             0
sellingprice    0
saledate        0
dtype: int64

In [15]:
df['saledate'].head(10)

0   2014-12-16 04:30:00+00:00
1   2014-12-16 04:30:00+00:00
2   2015-01-14 20:30:00+00:00
3   2015-01-28 20:30:00+00:00
4   2014-12-18 04:30:00+00:00
5   2014-12-30 04:00:00+00:00
6   2014-12-17 04:30:00+00:00
7   2014-12-16 05:00:00+00:00
8   2014-12-18 04:00:00+00:00
9   2015-01-19 20:00:00+00:00
Name: saledate, dtype: datetime64[us, UTC]

In [16]:
df['Sale_Year'] = df['saledate'].dt.year
df['Sale_Month'] = df['saledate'].dt.month_name()
df['Sale_Month_Num'] = df['saledate'].dt.month
df['Sale_Quarter'] = df['saledate'].dt.quarter
df['Sale_Day'] = df['saledate'].dt.day_name()

In [17]:
df[['saledate','Sale_Year','Sale_Month','Sale_Quarter']].head()

                   saledate  Sale_Year Sale_Month  Sale_Quarter
0 2014-12-16 04:30:00+00:00       2014   December             4
1 2014-12-16 04:30:00+00:00       2014   December             4
2 2015-01-14 20:30:00+00:00       2015    January             1
3 2015-01-28 20:30:00+00:00       2015    January             1
4 2014-12-18 04:30:00+00:00       2014   December             4

In [20]:
df['Vehicle_Age'] = df['Sale_Year'] - df['year']
df['Vehicle_Age'] = df['Vehicle_Age'].clip(lower=0)

In [21]:
df[['year','Sale_Year','Vehicle_Age']].head()

   year  Sale_Year  Vehicle_Age
0  2015       2014            0
1  2015       2014            0
2  2014       2015            1
3  2015       2015            0
4  2014       2014            0

In [22]:
df['Mileage_Band'] = pd.cut(
    df['odometer'],
    bins=[0, 25000, 50000, 100000, 150000, float('inf')],
    labels=[
        'Very Low',
        'Low',
        'Moderate',
        'High',
        'Very High'
    ]
)

In [23]:
df['Price_Range'] = pd.cut(
    df['sellingprice'],
    bins=[0,5000,10000,20000,40000,60000,float('inf')],
    labels=[
        'Entry',
        'Budget',
        'Economy',
        'Mid-Range',
        'Premium',
        'Luxury'
    ]
)

In [24]:
def vehicle_condition(x):
    if x >= 4:
        return 'Excellent'
    elif x >= 3:
        return 'Good'
    elif x >= 2:
        return 'Fair'
    else:
        return 'Poor'

df['Vehicle_Condition'] = df['condition'].apply(vehicle_condition)

In [27]:
df['Price_Difference'] = df['sellingprice'] - df['mmr']

In [28]:
def market_status(x):
    if x > 1000:
        return 'Sold Above Market'
    elif x < -1000:
        return 'Sold Below Market'
    else:
        return 'Sold Near Market'

df['Market_Status'] = df['Price_Difference'].apply(market_status)

In [29]:
df.head()

,year,make,model,trim,body,transmission,state,condition,odometer,color,...,Sale_Month,Sale_Month_Num,Sale_Quarter,Sale_Day,Vehicle_Age,Mileage_Band,Price_Range,Vehicle_Condition,Price_Difference,Market_Status
0,2015,Kia,Sorento,LX,SUV,automatic,ca,5.0,16639.0,white,...,December,12,4,Tuesday,0,Very Low,Mid-Range,Excellent,1000.0,Sold Near Market
1,2015,Kia,Sorento,LX,SUV,automatic,ca,5.0,9393.0,white,...,December,12,4,Tuesday,0,Very Low,Mid-Range,Excellent,700.0,Sold Near Market
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,ca,45.0,1331.0,gray,...,January,1,1,Wednesday,1,Very Low,Mid-Range,Excellent,-1900.0,Sold Below Market
3,2015,Volvo,S60,T5,Sedan,automatic,ca,41.0,14282.0,white,...,January,1,1,Wednesday,0,Very Low,Mid-Range,Excellent,250.0,Sold Near Market
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,ca,43.0,2641.0,gray,...,December,12,4,Thursday,0,Very Low,Luxury,Excellent,1000.0,Sold Near Market

In [30]:
df['condition'].describe()

count    548400.000000
mean         30.866534
std          13.246675
min           1.000000
25%          24.000000
50%          35.000000
75%          41.000000
max          49.000000
Name: condition, dtype: float64

In [31]:
def vehicle_condition(score):
    if score >= 40:
        return "Excellent"
    elif score >= 30:
        return "Good"
    elif score >= 20:
        return "Fair"
    else:
        return "Poor"

df['Vehicle_Condition'] = df['condition'].apply(vehicle_condition)

In [32]:
df['Vehicle_Condition'].value_counts()

Vehicle_Condition
Good         170942
Excellent    158440
Poor         110173
Fair         108845
Name: count, dtype: int64

In [34]:
df.to_csv("automotive_sales_cleaned.csv", index=False)